<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>txt</string>
	</array>
	<key>firstLineMatch</key>
	<string>Requirements</string>
	<key>keyEquivalent</key>
	<string>^~S</string>
	<key>name</key>
	<string>Stories</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>As\san?|I\swould\slike\sto|so\sthat</string>
			<key>name</key>
			<string>entity.name.tag.story</string>
			<key>spellChecking</key>
			<integer>1</integer>
		</dict>
		<dict>
			<key>match</key>
			<string>^([^\s][\w\s-]+):\s</string>
			<key>name</key>
			<string>entity.name.type.story</string>
			<key>spellChecking</key>
			<integer>1</integer>
		</dict>
		<dict>
			<key>match</key>
			<string>^([^\s][\w\s-]+)$</string>
			<key>name</key>
			<string>entity.name.section.story</string>
			<key>spellChecking</key>
			<integer>1</integer>
		</dict>
		<dict>
			<key>match</key>
			<string>^-(.*)$</string>
			<key>name</key>
			<string>markup.list.story</string>
			<key>spellChecking</key>
			<integer>1</integer>
		</dict>
		<dict>
			<key>match</key>
			<string>#\d+</string>
			<key>name</key>
			<string>constant.character.id.story</string>
		</dict>
		<dict>
			<key>match</key>
			<string>i\d+</string>
			<key>name</key>
			<string>constant.numeric.iteration.story</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\d+(d|h)</string>
			<key>name</key>
			<string>constant.numeric.estimate.story</string>
		</dict>
		<dict>
			<key>match</key>
			<string>could|should|must</string>
			<key>name</key>
			<string>constant.language.priority.story</string>
		</dict>
		<dict>
			<key>match</key>
			<string>todo|partial|done</string>
			<key>name</key>
			<string>constant.language.status.story</string>
		</dict>
		<dict>
			<key>match</key>
			<string>^\s*#[^\d].*$</string>
			<key>name</key>
			<string>comment</string>
			<key>spellChecking</key>
			<integer>1</integer>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.story</string>
	<key>spellChecking</key>
	<integer>1</integer>
	<key>uuid</key>
	<string>91BB0C3E-0AD9-40B7-BBAB-089FEAE209E4</string>
</dict>
</plist>
